<a href="https://colab.research.google.com/github/paweenatoei/KKU_data_mining/blob/master/Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [72]:
import pandas as pd
import os

In [73]:
from google.colab import drive
drive.mount('/content/drive')
#เป็นการนำเข้าไฟล์ข้อมูลจากไดร์ฟมายัง colab

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [74]:
path = '/content/drive/My Drive/TB_pro'
#path คือ การกำหนดตัวแปรให้เป็นที่อยู่ของไฟล์

In [75]:
tmdb_5000_movies = os.path.join(path,'tmdb_5000_movies.csv')
#สร้างที่อยู่โดยใช้ os.path.join

In [76]:
tmdb_5000_movies_df = pd.read_csv(tmdb_5000_movies)
tmdb_5000_movies_df

         budget  ... vote_count
0     237000000  ...      11800
1     300000000  ...       4500
2     245000000  ...       4466
3     250000000  ...       9106
4     260000000  ...       2124
...         ...  ...        ...
4798     220000  ...        238
4799       9000  ...          5
4800          0  ...          6
4801          0  ...          7
4802          0  ...         16

[4803 rows x 20 columns]

In [77]:
tmdb_5000_movies_df.isnull().any()
#เป็นการตรวจสอบว่าแต่ละคอลัมมีข้อมูลที่ขาดหายไหม

budget                  False
genres                  False
homepage                 True
movie_id                False
keywords                False
original_language       False
original_title          False
overview                 True
popularity              False
production_companies    False
production_countries    False
release_date             True
revenue                 False
runtime                  True
spoken_languages        False
status                  False
tagline                  True
title                   False
vote_average            False
vote_count              False
dtype: bool

In [78]:
tmdb_5000_credits = os.path.join(path,'tmdb_5000_credits.csv')

In [79]:
tmdb_5000_credits_df = pd.read_csv(tmdb_5000_credits)
tmdb_5000_credits_df

      movie_id  ...                                               crew
0        19995  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1          285  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2       206647  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3        49026  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4        49529  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
...        ...  ...                                                ...
4798      9367  ...  [{"credit_id": "52fe44eec3a36847f80b280b", "de...
4799     72766  ...  [{"credit_id": "52fe487dc3a368484e0fb013", "de...
4800    231617  ...  [{"credit_id": "52fe4df3c3a36847f8275ecf", "de...
4801    126186  ...  [{"credit_id": "52fe4ad9c3a368484e16a36b", "de...
4802     25975  ...  [{"credit_id": "58ce021b9251415a390165d9", "de...

[4803 rows x 4 columns]

In [80]:
tmdb_5000_credits_11 = os.path.join(path,'tmdb_5000_credits_11.csv')

In [81]:
tmdb_5000_credits_11_df = pd.read_csv(tmdb_5000_credits_11)
tmdb_5000_credits_11_df

      movie_id  ...                                               crew
0        19995  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1          285  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2       206647  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3        49026  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4        49529  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
...        ...  ...                                                ...
4798      9367  ...  [{"credit_id": "52fe44eec3a36847f80b280b", "de...
4799     72766  ...  [{"credit_id": "52fe487dc3a368484e0fb013", "de...
4800    231617  ...  [{"credit_id": "52fe4df3c3a36847f8275ecf", "de...
4801    126186  ...  [{"credit_id": "52fe4ad9c3a368484e16a36b", "de...
4802     25975  ...  [{"credit_id": "58ce021b9251415a390165d9", "de...

[4803 rows x 9 columns]

In [82]:
tmdb_5000_credits_11_df.isnull().any()

movie_id    False
title       False
cast1        True
cast2        True
cast3        True
cast4        True
cast5        True
cast_new     True
crew         True
dtype: bool

In [83]:
merge_tb = tmdb_5000_movies_df.merge(tmdb_5000_credits_11_df,how='left', left_on='movie_id',right_on='movie_id')
merge_tb

         budget  ...                                               crew
0     237000000  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1     300000000  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2     245000000  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3     250000000  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4     260000000  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
...         ...  ...                                                ...
4798     220000  ...  [{"credit_id": "52fe44eec3a36847f80b280b", "de...
4799       9000  ...  [{"credit_id": "52fe487dc3a368484e0fb013", "de...
4800          0  ...  [{"credit_id": "52fe4df3c3a36847f8275ecf", "de...
4801          0  ...  [{"credit_id": "52fe4ad9c3a368484e16a36b", "de...
4802          0  ...  [{"credit_id": "58ce021b9251415a390165d9", "de...

[4803 rows x 28 columns]

In [84]:
merge_tb[['vote_average','original_title','cast_new']]

      vote_average  ...                                           cast_new
0              7.2  ...   "Sam Worthington", "Zoe Saldana", "Stephen La...
1              6.9  ...   "Johnny Depp", "Orlando Bloom", "Stellan Skar...
2              6.3  ...   "Daniel Craig", "Christoph Waltz", "Ralph Fie...
3              7.6  ...   "Christian Bale", "Michael Caine", "Anne Hath...
4              6.1  ...   "Taylor Kitsch", "Lynn Collins", "Willem Dafo...
...            ...  ...                                                ...
4798           6.6  ...   "Carlos Gallardo", "Jaime de Hoyos", "Peter M...
4799           5.9  ...   "Edward Burns", "Kerry Bish\u00e9", "Marsha D...
4800           7.0  ...   "Eric Mabius", "Kristin Booth", "Crystal Lowe...
4801           5.7  ...   "Daniel Henney", "Eliza Coupe", "Bill Paxton"...
4802           6.3  ...   "Drew Barrymore", "Brian Herzlinger", "Corey ...

[4803 rows x 3 columns]

In [85]:
table = merge_tb.groupby('original_title')['cast_new'].apply(list)
table

original_title
#Horror                                 [ "Taryn Manning", "Natasha Lyonne", "Chlo\u00...
$upercapitalist                         [ "Linus Roache", "Derek Ting", "Richard Ng", ...
(500) Days of Summer                    [ "Joseph Gordon-Levitt", "Zooey Deschanel", "...
...E tu vivrai nel terrore! L'aldilà    [ "Catriona MacColl", "David Warbeck", "Cinzia...
10 Cloverfield Lane                     [ "Mary Elizabeth Winstead", "John Goodman", "...
                                                              ...
인천상륙작전                                  [ "Lee Jung-jae", "Liam Neeson", "Lee Beom-soo...
좋은 놈, 나쁜 놈, 이상한 놈                       [ "Song Kang-ho", "Lee Byung-hun", "Jung Woo-s...
친절한 금자씨                                 [ "Choi Min-sik", "Lee Young-ae", "Kwon Yea-yo...
태극기 휘날리며                                [ "Jang Dong-gun", "Won Bin", "Lee Eun-ju", "G...
해운대                                     [ "Park Joong-hoon", "Sol Kyung-gu", "Uhm Jung...
Name: cast_new, Length: 4801, dtype: object

In [86]:
table1 = merge_tb.groupby('vote_average')['cast_new'].apply(list)
table1

vote_average
0.0     [ "Laurence Fishburne", "Karl Urban", "Brittan...
0.5     [ "Melissa Leo", "Maggie Wheeler", "Joey D. Vi...
1.0     [ "Rachael Leigh Cook", "Luke Kirby", "Keith C...
1.9     [ "Jon Voight", "Scott Baio", "Vanessa Angel",...
2.0     [ "Joe Pantoliano", "Wade Dominguez", "Elizabe...
                              ...
8.4     [ "Ronald Colman", "Madeleine Carroll", "Raymo...
8.5     [ "Tim Robbins", "Morgan Freeman", "Bob Gunton...
9.3     [ "Tom Berenger", "Joaquim de Almeida", "Danie...
9.5                                                 [nan]
10.0    [ "Georgina Cates", "Peter Ustinov", "Prunella...
Name: cast_new, Length: 71, dtype: object

In [87]:
!pip install dp

Collecting dp
  Downloading https://files.pythonhosted.org/packages/6f/d3/e4c0b73823bfe308a9158aba84491d73ccb79400f66655f15f7aa1c673a1/dp-1.00.tar.gz
Building wheels for collected packages: dp
  Building wheel for dp (setup.py) ... done
  Created wheel for dp: filename=dp-1.0-cp36-none-any.whl size=1941 sha256=f308f91831a4712ba20d2633331059fafdf9172a33e2007d866c4f735a47fc9f
  Stored in directory: /root/.cache/pip/wheels/05/6d/56/f9ceffae10ec1ae2ffb86ea648c5064a2ddd54740a692879ac
Successfully built dp
Installing collected packages: dp
Successfully installed dp-1.0

#Drop missing value

เป็นการดรอป missing

In [88]:
merge_tb_dp = merge_tb.dropna()
merge_tb_dp

         budget  ...                                               crew
0     237000000  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1     300000000  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2     245000000  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3     250000000  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4     260000000  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
...         ...  ...                                                ...
4772      31192  ...  [{"credit_id": "52fe45f0c3a36847f80e3327", "de...
4773      27000  ...  [{"credit_id": "52fe434ac3a36847f8049253", "de...
4781      22000  ...  [{"credit_id": "52fe4ee39251416c911412e7", "de...
4796       7000  ...  [{"credit_id": "52fe45e79251416c75066791", "de...
4801          0  ...  [{"credit_id": "52fe4ad9c3a368484e16a36b", "de...

[1461 rows x 28 columns]

In [89]:
merge_tb_dp.isnull().any()

budget                  False
genres                  False
homepage                False
movie_id                False
keywords                False
original_language       False
original_title          False
overview                False
popularity              False
production_companies    False
production_countries    False
release_date            False
revenue                 False
runtime                 False
spoken_languages        False
status                  False
tagline                 False
title_x                 False
vote_average            False
vote_count              False
title_y                 False
cast1                   False
cast2                   False
cast3                   False
cast4                   False
cast5                   False
cast_new                False
crew                    False
dtype: bool

#Percent of missing data from dropna

In [90]:
size_before_drop = 4803
size_after_drop = 1493
print(f'size before drop = {size_before_drop} \nsize after drop = {size_after_drop}\nwhich is {100*((size_before_drop-size_after_drop)/size_before_drop)}')

size before drop = 4803
size after drop = 1493
which is 68.91526129502394

#Data Mining

In [92]:
table2 = merge_tb_dp[merge_tb_dp['vote_average']<= 5]
table2
#หาชื่อหนังที่มีคะแนนโหวตน้อยว่าหรือเท่ากับ5

         budget  ...                                               crew
91    165000000  ...  [{"credit_id": "5763d39cc3a36860a5000168", "de...
138   150000000  ...  [{"credit_id": "52fe433f9251416c750092c9", "de...
226   120000000  ...  [{"credit_id": "52fe4620c3a36847f80ee48d", "de...
242   120000000  ...  [{"credit_id": "566e93a9925141664f00eb4c", "de...
292   100000000  ...  [{"credit_id": "52fe435ac3a36847f804de45", "de...
...         ...  ...                                                ...
4569          0  ...  [{"credit_id": "52fe4d7b9251416c9111797f", "de...
4647     250000  ...  [{"credit_id": "586ace83c3a3686e2a0034fa", "de...
4701     150000  ...  [{"credit_id": "52fe4424c3a36847f8084a63", "de...
4723     100000  ...  [{"credit_id": "54951e769251413af7001c60", "de...
4765          0  ...  [{"credit_id": "52fe4ecf9251416c75163381", "de...

[111 rows x 28 columns]

In [93]:
table3 = merge_tb_dp[merge_tb_dp['vote_average']> 5]
table3
#เพื่อหาชื่อหนังที่มีคะแนนโหวตมากว่า5

         budget  ...                                               crew
0     237000000  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1     300000000  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2     245000000  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3     250000000  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4     260000000  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
...         ...  ...                                                ...
4772      31192  ...  [{"credit_id": "52fe45f0c3a36847f80e3327", "de...
4773      27000  ...  [{"credit_id": "52fe434ac3a36847f8049253", "de...
4781      22000  ...  [{"credit_id": "52fe4ee39251416c911412e7", "de...
4796       7000  ...  [{"credit_id": "52fe45e79251416c75066791", "de...
4801          0  ...  [{"credit_id": "52fe4ad9c3a368484e16a36b", "de...

[1350 rows x 28 columns]

In [94]:
table4 = table2.groupby('vote_average')['original_title'].apply(list)
table4
#ชื่อหนังที่มีคะแนนโหวตน้อยกว่าหรือเท่ากับ5

vote_average
0.0    [Should've Been Romeo, Time to Choose, House a...
1.9                       [Superbabies: Baby Geniuses 2]
2.3                                         [Foodfight!]
3.0                                     [Disaster Movie]
3.2                             [Doogal, Raymond Did It]
3.3                                  [Galaxina, #Horror]
3.5                 [Gigli, BloodRayne, $upercapitalist]
3.7                     [Meet the Spartans, Left Behind]
3.8                                          [Sharknado]
3.9    [Fight Valley, Standing Ovation, Atlas Shrugge...
4.1    [Jack and Jill, In the Name of the King: A Dun...
4.2                   [Vampires Suck, The Wicked Within]
4.3    [The Love Guru, The Country Bears, Dancin' It'...
4.4    [Fantastic Four, The Flintstones in Viva Rock ...
4.5    [The Shaggy Dog, Dylan Dog: Dead of Night, The...
4.6    [Happily N'Ever After, Furry Vengeance, Boogey...
4.7    [The Last Airbender, xXx: State of the Union, ...
4.8    [A Sound of Thunder, Elektra, The Darkest Hour...
4.9    [Independence Day: Resurgence, How Do You Know...
5.0    [I, Frankenstein, Cats & Dogs, Meet Dave, Marm...
Name: original_title, dtype: object

In [109]:
table7 = table2.groupby('vote_average')['cast_new'].apply(list)
table7

vote_average
0.0    [ "Paul Ben-Victor", "Ed Asner", "Jordenn Thom...
1.9    [ "Jon Voight", "Scott Baio", "Vanessa Angel",...
2.3    [ "Charlie Sheen", "Wayne Brady", "Hilary Duff...
3.0    [ "Matt Lanter", "Vanessa Lachey", "Nicole Ari...
3.2    [ "Daniel Tay", "Jimmy Fallon", "Jon Stewart",...
3.3    [ "Dorothy Stratten", "Stephen Macht", "Avery ...
3.5    [ "Ben Affleck", "Jennifer Lopez", "Justin Bar...
3.7    [ "Sean Maguire", "Carmen Electra", "Ken Davit...
3.8    [ "Ian Ziering", "Tara Reid", "Cassandra Scerb...
3.9    [ "Erin O'Brien", "Miesha Tate", "Holly Holm",...
4.1    [ "Adam Sandler", "Katie Holmes", "Al Pacino",...
4.2    [ "Chris Riggi", "Matt Lanter", "Jenn Proske",...
4.3    [ "Mike Myers", "Jessica Alba", "Justin Timber...
4.4    [ "Miles Teller", "Kate Mara", "Michael B. Jor...
4.5    [ "Tim Allen", "Kristin Davis", "Danny Glover"...
4.6    [ "George Carlin", "Andy Dick", "Sarah Michell...
4.7    [ "Noah Ringer", "Nicola Peltz", "Jackson Rath...
4.8    [ "Heike Makatsch", "Armin Rohde", "David Oyel...
4.9    [ "Liam Hemsworth", "Jeff Goldblum", "Bill Pul...
5.0    [ "Aaron Eckhart", "Yvonne Strahovski", "Bill ...
Name: cast_new, dtype: object

In [95]:
table5 = table3.groupby('vote_average')['original_title'].apply(list)
table5
#ชื่อหนังที่มีคะแนนโหวตมากกว่า5

vote_average
5.1    [Green Lantern, G-Force, Nine, Blackhat, The D...
5.2    [Jupiter Ascending, The Mummy: Tomb of the Dra...
5.3    [Evan Almighty, Ghostbusters, Ben-Hur, Zookeep...
5.4    [R.I.P.D., Little Fockers, Sex and the City 2,...
5.5    [Jack the Giant Slayer, The Legend of Tarzan, ...
5.6    [2012, G.I. Joe: The Rise of Cobra, Exodus: Go...
5.7    [Batman v Superman: Dawn of Justice, Oz: The G...
5.8    [The Golden Compass, Transformers: Age of Exti...
5.9    [Spider-Man 3, The Lone Ranger, Terminator Sal...
6.0    [Transformers: Revenge of the Fallen, Monsters...
6.1    [John Carter, Quantum of Solace, Transformers:...
6.2    [Men in Black 3, Robin Hood, Prince of Persia:...
6.3    [Spectre, TRON: Legacy, Warcraft, Bolt, Rio 2,...
6.4    [Pirates of the Caribbean: On Stranger Tides, ...
6.5    [Man of Steel, The Amazing Spider-Man, Jurassi...
6.6    [The Good Dinosaur, A Christmas Carol, Iron Ma...
6.7    [Spider-Man 2, World War Z, Pacific Rim, Brave...
6.8    [Iron Man 3, Thor: The Dark World, Mission: Im...
6.9    [Pirates of the Caribbean: At World's End, Sky...
7.0    [Pirates of the Caribbean: Dead Man's Chest, H...
7.1    [The Hobbit: The Battle of the Five Armies, Ca...
7.2    [Avatar, Mad Max: Fury Road, Life of Pi, The G...
7.3    [Avengers: Age of Ultron, Furious 7, Dawn of t...
7.4    [Tangled, Harry Potter and the Half-Blood Prin...
7.5    [Titanic, X-Men: Days of Future Past, How to T...
7.6    [The Dark Knight Rises, The Hobbit: The Desola...
7.7    [A Beautiful Mind, Kill Bill: Vol. 1, Catch Me...
7.8    [WALL·E, Big Hero 6, Django Unchained, Shutter...
7.9    [Guardians of the Galaxy, The Wolf of Wall Str...
8.0    [Inside Out, The Lord of the Rings: The Fellow...
8.1    [Interstellar, Inception, The Lord of the Ring...
8.2    [The Dark Knight, The Green Mile, GoodFellas, ...
8.3    [Fight Club, Schindler's List, 千と千尋の神隠し, Whipl...
8.4                                      [The Godfather]
Name: original_title, dtype: object

In [108]:
table6 = table3.groupby('vote_average')['cast_new'].apply(list)
table6

vote_average
5.1    [ "Ryan Reynolds", "Blake Lively", "Peter Sars...
5.2    [ "Mila Kunis", "Channing Tatum", "Sean Bean",...
5.3    [ "Steve Carell", "Lauren Graham", "John Goodm...
5.4    [ "Jeff Bridges", "Ryan Reynolds", "Kevin Baco...
5.5    [ "Nicholas Hoult", "Eleanor Tomlinson", "Ewan...
5.6    [ "John Cusack", "Amanda Peet", "Chiwetel Ejio...
5.7    [ "Ben Affleck", "Henry Cavill", "Amy Adams", ...
5.8    [ "Dakota Blue Richards", "Nicole Kidman", "Sa...
5.9    [ "Tobey Maguire", "Kirsten Dunst", "Thomas Ha...
6.0    [ "Shia LaBeouf", "Megan Fox", "Josh Duhamel",...
6.1    [ "Taylor Kitsch", "Lynn Collins", "Willem Daf...
6.2    [ "Will Smith", "Tommy Lee Jones", "Michael St...
6.3    [ "Daniel Craig", "Christoph Waltz", "Ralph Fi...
6.4    [ "Johnny Depp", "Pen\u00e9lope Cruz", "Kevin ...
6.5    [ "Henry Cavill", "Amy Adams", "Kevin Costner"...
6.6    [ "Raymond Ochoa", "Jack Bright", "Jeffrey Wri...
6.7    [ "Tobey Maguire", "Kirsten Dunst", "James Fra...
6.8    [ "Robert Downey Jr.", "Gwyneth Paltrow", "Don...
6.9    [ "Johnny Depp", "Orlando Bloom", "Stellan Ska...
7.0    [ "Johnny Depp", "Orlando Bloom", "Stellan Ska...
7.1    [ "Martin Freeman", "Ian McKellen", "Ken Stott...
7.2    [ "Sam Worthington", "Zoe Saldana", "Stephen L...
7.3    [ "Robert Downey Jr.", "Chris Hemsworth", "Chr...
7.4    [ "Zachary Levi", "Mandy Moore", "Ron Perlman"...
7.5    [ "Kate Winslet", "Leonardo DiCaprio", "Billy ...
7.6    [ "Christian Bale", "Michael Caine", "Anne Hat...
7.7    [ "Russell Crowe", "Ed Harris", "Jennifer Conn...
7.8    [ "Ben Burtt", "Elissa Knight", "Jeff Garlin",...
7.9    [ "Chris Pratt", "Zoe Saldana", "Dave Bautista...
8.0    [ "Amy Poehler", "Phyllis Smith", "Richard Kin...
8.1    [ "Matthew McConaughey", "Jessica Chastain", "...
8.2    [ "Christian Bale", "Heath Ledger", "Aaron Eck...
8.3    [ "Edward Norton", "Brad Pitt", "Meat Loaf", "...
8.4    [ "Marlon Brando", "Al Pacino", "James Caan", ...
Name: cast_new, dtype: object

In [96]:
table2[['vote_average','original_title','cast_new']]
#กลุ่มที่มีคะแนนโหวตน้อยกว่าหรือเท่ากับ5 โดยเลือกดูแค่ 'vote_average', 'original_title', 'cast_new'

      vote_average  ...                                           cast_new
91             4.9  ...   "Liam Hemsworth", "Jeff Goldblum", "Bill Pull...
138            4.7  ...   "Noah Ringer", "Nicola Peltz", "Jackson Rathb...
226            4.9  ...   "Reese Witherspoon", "Paul Rudd", "Owen Wilso...
242            4.4  ...   "Miles Teller", "Kate Mara", "Michael B. Jord...
292            4.9  ...   "Ed Speleers", "Jeremy Irons", "Sienna Guillo...
...            ...  ...                                                ...
4569           0.0  ...   "Caitlin Fitzgerald", "Cheyenne Jackson", "Pe...
4647           4.1  ...   "Lindsay Lohan", "James Deen", "Gus Van Sant"...
4701           4.6  ...   "Simon Chuckster", "Melvin Van Peebles", "Hub...
4723           4.9  ...   "Cassidy Gifford", "Ryan Shoos", "Pfeifer Bro...
4765           3.2  ...   "Kyle Hoskins", "Elissa Dowling", "Linda Cies...

[111 rows x 3 columns]

In [97]:
table3[['vote_average','original_title','cast_new']]
#กลุ่มที่มีคะแนนโหวตมากกว่า5 โดยเลือกดูแค่ 'vote_average', 'original_title', 'cast_new'

      vote_average  ...                                           cast_new
0              7.2  ...   "Sam Worthington", "Zoe Saldana", "Stephen La...
1              6.9  ...   "Johnny Depp", "Orlando Bloom", "Stellan Skar...
2              6.3  ...   "Daniel Craig", "Christoph Waltz", "Ralph Fie...
3              7.6  ...   "Christian Bale", "Michael Caine", "Anne Hath...
4              6.1  ...   "Taylor Kitsch", "Lynn Collins", "Willem Dafo...
...            ...  ...                                                ...
4772           6.3  ...   "Robert Hill", "Robin Hill", "Julia Deakin", ...
4773           7.4  ...   "Brian O'Halloran", "Jeff Anderson", "Jason M...
4781           6.0  ...   "Suzi Lorraine", "Jared Degado", "Heather Dor...
4796           6.9  ...   "Shane Carruth", "David Sullivan", "Casey Goo...
4801           5.7  ...   "Daniel Henney", "Eliza Coupe", "Bill Paxton"...

[1350 rows x 3 columns]

In [98]:
!pip install apyori

Requirement already satisfied: apyori in /usr/local/lib/python3.6/dist-packages (1.1.2)

In [99]:
from apyori import apriori

In [111]:
watch = list(apriori(table2, min_support = 0.3 , min_confidence = 0.8))
watch

[RelationRecord(items=frozenset({'_', 'e'}), support=0.42857142857142855, ordered_statistics=[OrderedStatistic(items_base=frozenset({'_'}), items_add=frozenset({'e'}), confidence=1.0, lift=1.3333333333333333)]),
 RelationRecord(items=frozenset({'a', 't'}), support=0.4642857142857143, ordered_statistics=[OrderedStatistic(items_base=frozenset({'a'}), items_add=frozenset({'t'}), confidence=0.8125000000000001, lift=1.1973684210526316)]),
 RelationRecord(items=frozenset({'c', 't'}), support=0.32142857142857145, ordered_statistics=[OrderedStatistic(items_base=frozenset({'c'}), items_add=frozenset({'t'}), confidence=0.9, lift=1.3263157894736841)]),
 RelationRecord(items=frozenset({'e', 'i'}), support=0.35714285714285715, ordered_statistics=[OrderedStatistic(items_base=frozenset({'i'}), items_add=frozenset({'e'}), confidence=0.9090909090909092, lift=1.2121212121212122)]),
 RelationRecord(items=frozenset({'n', 'e'}), support=0.39285714285714285, ordered_statistics=[OrderedStatistic(items_base=frozenset({'n'}), items_add=frozenset({'e'}), confidence=1.0, lift=1.3333333333333333)]),
 RelationRecord(items=frozenset({'e', 'o'}), support=0.39285714285714285, ordered_statistics=[OrderedStatistic(items_base=frozenset({'o'}), items_add=frozenset({'e'}), confidence=0.9166666666666667, lift=1.2222222222222223)]),
 RelationRecord(items=frozenset({'e', 'r'}), support=0.42857142857142855, ordered_statistics=[OrderedStatistic(items_base=frozenset({'r'}), items_add=frozenset({'e'}), confidence=0.923076923076923, lift=1.2307692307692306)]),
 RelationRecord(items=frozenset({'_', 'e', 't'}), support=0.32142857142857145, ordered_statistics=[OrderedStatistic(items_base=frozenset({'_', 't'}), items_add=frozenset({'e'}), confidence=1.0, lift=1.3333333333333333)]),
 RelationRecord(items=frozenset({'s', 'a', 't'}), support=0.32142857142857145, ordered_statistics=[OrderedStatistic(items_base=frozenset({'s', 'a'}), items_add=frozenset({'t'}), confidence=0.9, lift=1.3263157894736841), OrderedStatistic(items_base=frozenset({'s', 't'}), items_add=frozenset({'a'}), confidence=0.9, lift=1.5750000000000002)])]

In [102]:
watch = list(apriori(table3, min_support = 0.3 , min_confidence = 0.8))
watch

[RelationRecord(items=frozenset({'_', 'e'}), support=0.42857142857142855, ordered_statistics=[OrderedStatistic(items_base=frozenset({'_'}), items_add=frozenset({'e'}), confidence=1.0, lift=1.3333333333333333)]),
 RelationRecord(items=frozenset({'a', 't'}), support=0.4642857142857143, ordered_statistics=[OrderedStatistic(items_base=frozenset({'a'}), items_add=frozenset({'t'}), confidence=0.8125000000000001, lift=1.1973684210526316)]),
 RelationRecord(items=frozenset({'c', 't'}), support=0.32142857142857145, ordered_statistics=[OrderedStatistic(items_base=frozenset({'c'}), items_add=frozenset({'t'}), confidence=0.9, lift=1.3263157894736841)]),
 RelationRecord(items=frozenset({'e', 'i'}), support=0.35714285714285715, ordered_statistics=[OrderedStatistic(items_base=frozenset({'i'}), items_add=frozenset({'e'}), confidence=0.9090909090909092, lift=1.2121212121212122)]),
 RelationRecord(items=frozenset({'n', 'e'}), support=0.39285714285714285, ordered_statistics=[OrderedStatistic(items_base=frozenset({'n'}), items_add=frozenset({'e'}), confidence=1.0, lift=1.3333333333333333)]),
 RelationRecord(items=frozenset({'e', 'o'}), support=0.39285714285714285, ordered_statistics=[OrderedStatistic(items_base=frozenset({'o'}), items_add=frozenset({'e'}), confidence=0.9166666666666667, lift=1.2222222222222223)]),
 RelationRecord(items=frozenset({'e', 'r'}), support=0.42857142857142855, ordered_statistics=[OrderedStatistic(items_base=frozenset({'r'}), items_add=frozenset({'e'}), confidence=0.923076923076923, lift=1.2307692307692306)]),
 RelationRecord(items=frozenset({'_', 'e', 't'}), support=0.32142857142857145, ordered_statistics=[OrderedStatistic(items_base=frozenset({'_', 't'}), items_add=frozenset({'e'}), confidence=1.0, lift=1.3333333333333333)]),
 RelationRecord(items=frozenset({'s', 'a', 't'}), support=0.32142857142857145, ordered_statistics=[OrderedStatistic(items_base=frozenset({'s', 'a'}), items_add=frozenset({'t'}), confidence=0.9, lift=1.3263157894736841), OrderedStatistic(items_base=frozenset({'s', 't'}), items_add=frozenset({'a'}), confidence=0.9, lift=1.5750000000000002)])]

#Summary
###จากการทำ Association Rule ที่มี Vote_average น้อยกว่าหรือเท่ากับ5 และ มากกว่า 5 คะแนน แล้ว จะเห็นได้ว่า