<a href="https://colab.research.google.com/github/paweenatoei/KKU_data_mining/blob/master/Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
import pandas as pd
import os

In [52]:
from google.colab import drive
drive.mount('/content/drive')
#เป็นการนำเข้าไฟล์ข้อมูลจากไดร์ฟมายัง colab

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [53]:
path = '/content/drive/My Drive/TB_pro'
#path คือ การกำหนดตัวแปรให้เป็นที่อยู่ของไฟล์

In [54]:
tmdb_5000_movies = os.path.join(path,'tmdb_5000_movies.csv')
#สร้างที่อยู่โดยใช้ os.path.join

In [55]:
tmdb_5000_movies_df = pd.read_csv(tmdb_5000_movies)
tmdb_5000_movies_df

         budget  ... vote_count
0     237000000  ...      11800
1     300000000  ...       4500
2     245000000  ...       4466
3     250000000  ...       9106
4     260000000  ...       2124
...         ...  ...        ...
4798     220000  ...        238
4799       9000  ...          5
4800          0  ...          6
4801          0  ...          7
4802          0  ...         16

[4803 rows x 20 columns]

In [56]:
tmdb_5000_movies_df.isnull().any()
#เป็นการตรวจสอบว่าแต่ละคอลัมมีข้อมูลที่ขาดหายไหม

budget                  False
genres                  False
homepage                 True
movie_id                False
keywords                False
original_language       False
original_title          False
overview                 True
popularity              False
production_companies    False
production_countries    False
release_date             True
revenue                 False
runtime                  True
spoken_languages        False
status                  False
tagline                  True
title                   False
vote_average            False
vote_count              False
dtype: bool

In [57]:
tmdb_5000_credits = os.path.join(path,'tmdb_5000_credits.csv')

In [58]:
tmdb_5000_credits_df = pd.read_csv(tmdb_5000_credits)
tmdb_5000_credits_df

      movie_id  ...                                               crew
0        19995  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1          285  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2       206647  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3        49026  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4        49529  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
...        ...  ...                                                ...
4798      9367  ...  [{"credit_id": "52fe44eec3a36847f80b280b", "de...
4799     72766  ...  [{"credit_id": "52fe487dc3a368484e0fb013", "de...
4800    231617  ...  [{"credit_id": "52fe4df3c3a36847f8275ecf", "de...
4801    126186  ...  [{"credit_id": "52fe4ad9c3a368484e16a36b", "de...
4802     25975  ...  [{"credit_id": "58ce021b9251415a390165d9", "de...

[4803 rows x 4 columns]

In [59]:
tmdb_5000_credits_11 = os.path.join(path,'tmdb_5000_credits_11.csv')

In [60]:
tmdb_5000_credits_11_df = pd.read_csv(tmdb_5000_credits_11)
tmdb_5000_credits_11_df

      movie_id  ...                                               crew
0        19995  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1          285  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2       206647  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3        49026  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4        49529  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
...        ...  ...                                                ...
4798      9367  ...  [{"credit_id": "52fe44eec3a36847f80b280b", "de...
4799     72766  ...  [{"credit_id": "52fe487dc3a368484e0fb013", "de...
4800    231617  ...  [{"credit_id": "52fe4df3c3a36847f8275ecf", "de...
4801    126186  ...  [{"credit_id": "52fe4ad9c3a368484e16a36b", "de...
4802     25975  ...  [{"credit_id": "58ce021b9251415a390165d9", "de...

[4803 rows x 9 columns]

In [61]:
tmdb_5000_credits_11_df.isnull().any()

movie_id    False
title       False
cast1        True
cast2        True
cast3        True
cast4        True
cast5        True
cast_new     True
crew         True
dtype: bool

In [62]:
merge_tb = tmdb_5000_movies_df.merge(tmdb_5000_credits_11_df,how='left', left_on='movie_id',right_on='movie_id')
merge_tb

         budget  ...                                               crew
0     237000000  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1     300000000  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2     245000000  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3     250000000  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4     260000000  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
...         ...  ...                                                ...
4798     220000  ...  [{"credit_id": "52fe44eec3a36847f80b280b", "de...
4799       9000  ...  [{"credit_id": "52fe487dc3a368484e0fb013", "de...
4800          0  ...  [{"credit_id": "52fe4df3c3a36847f8275ecf", "de...
4801          0  ...  [{"credit_id": "52fe4ad9c3a368484e16a36b", "de...
4802          0  ...  [{"credit_id": "58ce021b9251415a390165d9", "de...

[4803 rows x 28 columns]

In [63]:
merge_tb[['vote_average','original_title','cast_new']]

      vote_average  ...                                           cast_new
0              7.2  ...   "Sam Worthington", "Zoe Saldana", "Stephen La...
1              6.9  ...   "Johnny Depp", "Orlando Bloom", "Stellan Skar...
2              6.3  ...   "Daniel Craig", "Christoph Waltz", "Ralph Fie...
3              7.6  ...   "Christian Bale", "Michael Caine", "Anne Hath...
4              6.1  ...   "Taylor Kitsch", "Lynn Collins", "Willem Dafo...
...            ...  ...                                                ...
4798           6.6  ...   "Carlos Gallardo", "Jaime de Hoyos", "Peter M...
4799           5.9  ...   "Edward Burns", "Kerry Bish\u00e9", "Marsha D...
4800           7.0  ...   "Eric Mabius", "Kristin Booth", "Crystal Lowe...
4801           5.7  ...   "Daniel Henney", "Eliza Coupe", "Bill Paxton"...
4802           6.3  ...   "Drew Barrymore", "Brian Herzlinger", "Corey ...

[4803 rows x 3 columns]

In [64]:
table = merge_tb.groupby('original_title')['cast_new'].apply(list)
table

original_title
#Horror                                 [ "Taryn Manning", "Natasha Lyonne", "Chlo\u00...
$upercapitalist                         [ "Linus Roache", "Derek Ting", "Richard Ng", ...
(500) Days of Summer                    [ "Joseph Gordon-Levitt", "Zooey Deschanel", "...
...E tu vivrai nel terrore! L'aldilà    [ "Catriona MacColl", "David Warbeck", "Cinzia...
10 Cloverfield Lane                     [ "Mary Elizabeth Winstead", "John Goodman", "...
                                                              ...
인천상륙작전                                  [ "Lee Jung-jae", "Liam Neeson", "Lee Beom-soo...
좋은 놈, 나쁜 놈, 이상한 놈                       [ "Song Kang-ho", "Lee Byung-hun", "Jung Woo-s...
친절한 금자씨                                 [ "Choi Min-sik", "Lee Young-ae", "Kwon Yea-yo...
태극기 휘날리며                                [ "Jang Dong-gun", "Won Bin", "Lee Eun-ju", "G...
해운대                                     [ "Park Joong-hoon", "Sol Kyung-gu", "Uhm Jung...
Name: cast_new, Length: 4801, dtype: object

In [65]:
table1 = merge_tb.groupby('vote_average')['cast_new'].apply(list)
table1

vote_average
0.0     [ "Laurence Fishburne", "Karl Urban", "Brittan...
0.5     [ "Melissa Leo", "Maggie Wheeler", "Joey D. Vi...
1.0     [ "Rachael Leigh Cook", "Luke Kirby", "Keith C...
1.9     [ "Jon Voight", "Scott Baio", "Vanessa Angel",...
2.0     [ "Joe Pantoliano", "Wade Dominguez", "Elizabe...
                              ...
8.4     [ "Ronald Colman", "Madeleine Carroll", "Raymo...
8.5     [ "Tim Robbins", "Morgan Freeman", "Bob Gunton...
9.3     [ "Tom Berenger", "Joaquim de Almeida", "Danie...
9.5                                                 [nan]
10.0    [ "Georgina Cates", "Peter Ustinov", "Prunella...
Name: cast_new, Length: 71, dtype: object

In [113]:
!pip install dp

Collecting dp
  Downloading https://files.pythonhosted.org/packages/6f/d3/e4c0b73823bfe308a9158aba84491d73ccb79400f66655f15f7aa1c673a1/dp-1.00.tar.gz
Building wheels for collected packages: dp
  Building wheel for dp (setup.py) ... done
  Created wheel for dp: filename=dp-1.0-cp36-none-any.whl size=1941 sha256=0669e59fc7c36b25f7efc19f1563c92c09c2942ea05ec3c0a55aeb880b2b9a7d
  Stored in directory: /root/.cache/pip/wheels/05/6d/56/f9ceffae10ec1ae2ffb86ea648c5064a2ddd54740a692879ac
Successfully built dp
Installing collected packages: dp
Successfully installed dp-1.0

In [115]:
table2 = merge_tb_dp[merge_tb_dp['vote_average']<= 5]
table2
#หาชื่อหนังที่มีคะแนนโหวตน้อยว่าหรือเท่ากับ5

         budget  ...                                               crew
91    165000000  ...  [{"credit_id": "5763d39cc3a36860a5000168", "de...
138   150000000  ...  [{"credit_id": "52fe433f9251416c750092c9", "de...
226   120000000  ...  [{"credit_id": "52fe4620c3a36847f80ee48d", "de...
242   120000000  ...  [{"credit_id": "566e93a9925141664f00eb4c", "de...
292   100000000  ...  [{"credit_id": "52fe435ac3a36847f804de45", "de...
...         ...  ...                                                ...
4569          0  ...  [{"credit_id": "52fe4d7b9251416c9111797f", "de...
4647     250000  ...  [{"credit_id": "586ace83c3a3686e2a0034fa", "de...
4701     150000  ...  [{"credit_id": "52fe4424c3a36847f8084a63", "de...
4723     100000  ...  [{"credit_id": "54951e769251413af7001c60", "de...
4765          0  ...  [{"credit_id": "52fe4ecf9251416c75163381", "de...

[111 rows x 28 columns]

In [116]:
table3 = merge_tb_dp[merge_tb_dp['vote_average']> 5]
table3
#เพื่อหาชื่อหนังที่มีคะแนนโหวตมากว่า5

         budget  ...                                               crew
0     237000000  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1     300000000  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2     245000000  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3     250000000  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4     260000000  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
...         ...  ...                                                ...
4772      31192  ...  [{"credit_id": "52fe45f0c3a36847f80e3327", "de...
4773      27000  ...  [{"credit_id": "52fe434ac3a36847f8049253", "de...
4781      22000  ...  [{"credit_id": "52fe4ee39251416c911412e7", "de...
4796       7000  ...  [{"credit_id": "52fe45e79251416c75066791", "de...
4801          0  ...  [{"credit_id": "52fe4ad9c3a368484e16a36b", "de...

[1350 rows x 28 columns]

In [117]:
table2[['vote_average','original_title','cast_new']]
#กลุ่มที่มีคะแนนโหวตน้อยกว่าหรือเท่ากับ5 โดยเลือกดูแค่ 'vote_average', 'original_title', 'cast_new'

      vote_average  ...                                           cast_new
91             4.9  ...   "Liam Hemsworth", "Jeff Goldblum", "Bill Pull...
138            4.7  ...   "Noah Ringer", "Nicola Peltz", "Jackson Rathb...
226            4.9  ...   "Reese Witherspoon", "Paul Rudd", "Owen Wilso...
242            4.4  ...   "Miles Teller", "Kate Mara", "Michael B. Jord...
292            4.9  ...   "Ed Speleers", "Jeremy Irons", "Sienna Guillo...
...            ...  ...                                                ...
4569           0.0  ...   "Caitlin Fitzgerald", "Cheyenne Jackson", "Pe...
4647           4.1  ...   "Lindsay Lohan", "James Deen", "Gus Van Sant"...
4701           4.6  ...   "Simon Chuckster", "Melvin Van Peebles", "Hub...
4723           4.9  ...   "Cassidy Gifford", "Ryan Shoos", "Pfeifer Bro...
4765           3.2  ...   "Kyle Hoskins", "Elissa Dowling", "Linda Cies...

[111 rows x 3 columns]

In [118]:
table3[['vote_average','original_title','cast_new']]
#กลุ่มที่มีคะแนนโหวตมากกว่า5 โดยเลือกดูแค่ 'vote_average', 'original_title', 'cast_new'

      vote_average  ...                                           cast_new
0              7.2  ...   "Sam Worthington", "Zoe Saldana", "Stephen La...
1              6.9  ...   "Johnny Depp", "Orlando Bloom", "Stellan Skar...
2              6.3  ...   "Daniel Craig", "Christoph Waltz", "Ralph Fie...
3              7.6  ...   "Christian Bale", "Michael Caine", "Anne Hath...
4              6.1  ...   "Taylor Kitsch", "Lynn Collins", "Willem Dafo...
...            ...  ...                                                ...
4772           6.3  ...   "Robert Hill", "Robin Hill", "Julia Deakin", ...
4773           7.4  ...   "Brian O'Halloran", "Jeff Anderson", "Jason M...
4781           6.0  ...   "Suzi Lorraine", "Jared Degado", "Heather Dor...
4796           6.9  ...   "Shane Carruth", "David Sullivan", "Casey Goo...
4801           5.7  ...   "Daniel Henney", "Eliza Coupe", "Bill Paxton"...

[1350 rows x 3 columns]

In [44]:
!pip install apyori

Collecting apyori
  Downloading https://files.pythonhosted.org/packages/5e/62/5ffde5c473ea4b033490617ec5caa80d59804875ad3c3c57c0976533a21a/apyori-1.1.2.tar.gz
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-cp36-none-any.whl size=5975 sha256=f09fb54fc068ecdd9b336eb8fe463930dab64e4a8ea9cbe213a0d65c6fd5fd17
  Stored in directory: /root/.cache/pip/wheels/5d/92/bb/474bbadbc8c0062b9eb168f69982a0443263f8ab1711a8cad0
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

In [45]:
from apyori import apriori

In [47]:
list(apriori(table1, min_support = 0.3 , min_confidence = 0.8))

TypeError: ignored